steps:
  build-and-push:
    image: plugins/docker
    privileged: true
    settings:
      registry: 192.168.1.20:5000
      repo: 192.168.1.20:5000/refarmer-v2
      tags:
        - latest
      insecure: true
      daemon_off: false
