steps:
  build-and-push:
    image: gcr.io/kaniko-project/executor:latest
    commands:
      - /kaniko/executor 
        --context=/woodpecker/src
        --dockerfile=Dockerfile
        --destination=192.168.1.20:5000/refarmer-v2:latest
        --insecure
        --skip-tls-verify
