steps:
  build-and-push:
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    settings:
      repo: 192.168.1.20:5000/refarmer-v2
      tags: latest
      registry: 192.168.1.20:5000
      insecure: true  # for local registry without TLS
    when:
      branch: v3
      event: v3
